### ISSUE TITLE
[Modules] EPIC Refactor number-generator-data

### ISSUE THREAD

**Issue by NicoleNG18** [codbex/codbex-olympus#258]
1. Refactor number generator's numbers.csv file:
   - remove Credit note
   - remove Debit note
   - reorder other items
2.  Change number for generation for each item with the new number

- [x]  codbex/codbex-jobs
- [x] codbex/codbex-orders
- [x] codbex/codbex-vacations
- [x] codbex/codbex-assets
- [x] codbex/codbex-payments
- [x] codbex/codbex-projects
- [x] codbex/codbex-inventory
- [x] codbex/codbex-contracts
- [x] codbex/codbex-employees
- [x] codbex/codbex-invoices
