### ISSUE TITLE
[Modules] EPIC - Refactor Modules

### ISSUE THREAD

**Issue by TIVMOF** [codbex/codbex-olympus#270]
General Refactoring on Modules:
---
- General regeneration to keep them updated with the changes of the Templates
- Adding roles to entities, reports, widgets and navigations. Bellow is explained the process to do so
- To implement the Create New functionality in entities. Primary entities need to apply the Manage Master Entities Layout type for this to work.
- To check if widgets redirect to the correct view or if they redirect at all as described in #356 
- To refactor service file where needed as described in #314 
- To refactor long names of entities as described in #116 
- Update readme.md files with up to date models

Steps to add roles to modules:
---
- Adding roles to entities
  1. Choose an entity and open its properties. Go to the Security tab
  2. Check the Generate Default Roles checkbox
  3. Do the same for every entity
  4. Regenerate the project
- Adding roles to reports
  1. Choose a report in a project and scroll down to its Security section
  2. Check the Generate Default Roles checkbox
  3. Regenerate the report
- Adding roles to navigation and widgets
  1. Choose a widget or navigation
  2. Find its extension file
  3. In the role field add the roles you want to access this widget or navigation by separating them with commas. The roles for the respectful module you can find in the gen folder of the edm in a roles folder.
  4. Do the same for all widgets and navigations
- Adding roles to extension projects (list bellow)
  1. Find the extension of the module
  2. In the role field add the roles you want to access this widget or navigation by separating them with commas. The roles for the respectful module you can find in the gen folder of the edm in a roles folder.

Module that need roles:
---
- [x] [codbex-currencies](https://github.com/codbex/codbex-currencies)
- [x] [codbex-accounts](https://github.com/codbex/codbex-accounts) 
- [x] [codbex-uoms](https://github.com/codbex/codbex-uoms) 
- [x] [codbex-industries](https://github.com/codbex/codbex-industries)
- [x] [codbex-methods](https://github.com/codbex/codbex-methods)
- [x] [codbex-vacations](https://github.com/codbex/codbex-vacations) 
- [x] [codbex-cities](https://github.com/codbex/codbex-cities) 
- [x] [codbex-companies](https://github.com/codbex/codbex-companies)
- [x] [codbex-partners](https://github.com/codbex/codbex-partners) 
- [x] [codbex-jobs](https://github.com/codbex/codbex-jobs)
- [x] [codbex-contracts](https://github.com/codbex/codbex-contracts)
- [x] [codbex-products](https://github.com/codbex/codbex-products) 
- [x] [codbex-organizations](https://github.com/codbex/codbex-organizations)
- [x] [codbex-employees](https://github.com/codbex/codbex-employees) 
- [x] [codbex-rfqs](https://github.com/codbex/codbex-rfqs)
- [x] [codbex-bids](https://github.com/codbex/codbex-bids) 
- [x] [codbex-inventory](https://github.com/codbex/codbex-inventory) 
- [x] [codbex-projects](https://github.com/codbex/codbex-projects) 
- [x] [codbex-salaries](https://github.com/codbex/codbex-salaries) 
- [x] [codbex-payments](https://github.com/codbex/codbex-payments) 
- [x] [codbex-payrolls](https://github.com/codbex/codbex-payrolls) 
- [x] [codbex-orders](https://github.com/codbex/codbex-orders) 
- [x] [codbex-invoices](https://github.com/codbex/codbex-invoices)
- [x] [codbex-opportunities](https://github.com/codbex/codbex-opportunities)
- [x] [codbex-assets](https://github.com/codbex/codbex-assets)
- [x] [codbex-appointments](https://github.com/codbex/codbex-appointments) 

Extension modules that need a role to be specified in their extension files
---
- [x] [codbex-order-inventory-ext](https://github.com/codbex/codbex-order-inventory-ext)
- [x] [codbex-order-invoice-ext](https://github.com/codbex/codbex-order-invoice-ext)
- [x] [codbex-invoice-inventory-ext](https://github.com/codbex/codbex-invoice-inventory-ext)
- [x] [codbex-order-payment-ext](https://github.com/codbex/codbex-order-payment-ext)
- [x] [codbex-payment-order-ext](https://github.com/codbex/codbex-payment-order-ext)
- [x] [codbex-payment-invoice-ext](https://github.com/codbex/codbex-payment-invoice-ext)
- [x] [codbex-lead-customer-ext](https://github.com/codbex/codbex-lead-customer-ext)
- [x] [codbex-disposal-waste-ext](https://github.com/codbex/codbex-disposal-waste-ext) 
- [x] [codbex-disposal-orders-ext](https://github.com/codbex/codbex-disposal-orders-ext)

**Comment by TIVMOF** [comment]
BLOCKED DUE: https://github.com/eclipse/dirigible/issues/4526
BLOCKED DUE: https://github.com/eclipse/dirigible/issues/4522

**Comment by TIVMOF** [comment]
This issue:
- fixes #356 
- fixes #314 
- fixes #116

**Comment by TIVMOF** [comment]
Epic Done
